name: Notify Discord on Release

on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -X POST "$DISCORD_WEBHOOK" \
          -H "Content-Type: application/json" \
          -d '{
            "content": "@everyone 📢 **Có bản phát hành mới cho Hyggshi OS!**",
            "username": "Hyggshi Bot",
            "avatar_url": "https://i.imgur.com/GD0Rvy4.png",
            "embeds": [{
              "title": "📦 Release: ${{ github.event.release.tag_name }}",
              "description": "${{ github.event.release.body }}",
              "url": "${{ github.event.release.html_url }}",
              "color": 16711680,
              "footer": {
                "text": "Hyggshi OS Project Center"
              },
              "timestamp": "${{ github.event.release.published_at }}"
            }]
          }'
